version: '2'

env:
  grafana_host: https://stats.serlo.local
  grafana_password: admin
  env_name: minikube
  infrastructure_repo: ../infrastructure/minikube/kpi

includes:
  build:    tasks/build.yml
  log:      tasks/log.yml
  project:  tasks/project.yml
  grafana:  tasks/grafana_minikube.yml
  cluster:  '../infrastructure/tasks/minikube.yml'
  terraform: tasks/terraform.yml

tasks:
  default:
    cmds:
      - task -l