version: 2

tasks:
  create: 
    desc: |
      *
        - ensures cluster is created
        - deploys the resources
        - launches the website
    cmds: 
      - task: minikube:create
      - task: deploy
      - task: launch

  start:
    desc: |
      *
        - ensures cluster is started
        - launches the website    
    cmds:
      - task: minikube:start
      - task: launch

  deploy:
    desc: |
      *
        - [minikube] builds the images in case they are not present in remote docker
        - applies the resources with terraform
    cmds:
      - task: build:all
      - task: terraform:apply
      - task: upload_athene2_dump

  launch:
    desc: |
      *
        - launches the grafana web app
        - [minikube] basic auth user and password is serlo
    cmds:
      - xdg-open $grafana_host 2>/dev/null >/dev/null

  download_athene2_dump:
    cmds:
      - mkdir -p tmp && echo "downloading latest mysql dump from gcloud" && gsutil cp {{.dump_location}} tmp/dump.zip
      - unzip tmp/dump.zip -d tmp
    status:
      - test -f tmp/dump.sql

  upload_athene2_dump:
    deps: [download_athene2_dump]
    cmds:
      - bash scripts/setup-athene2-db.sh
