defaults: &defaults

make_build: &make_build
  name: make build
  command: cd importer && make docker-build

version: 2.1
jobs:
  build:
    <<: *make_build

workflows:
  version: 2
  workflow:
    jobs:
      - build:
