version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
#    docker:
#      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          command: |
            sudo apt update -y
            sudo apt install -y lsb-release curl gnupg2 build-essential software-properties-common apt-transport-https
            export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt update -y && sudo apt install google-cloud-sdk -y
      - run:
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud auth configure-docker --quiet
      - run: 'cd mysql-importer && make docker-build'
      - run: 'cd mysql-importer && make docker-push'
      - run: 'cd athene2-content-provider && make docker-build'
      - run: 'cd athene2-content-provider && make docker-push'
      - run: 'cd aggregator && make docker-build'
      - run: 'cd aggregator && make docker-push'

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: serlo-containers

