Scheduler:
        IntervalInMin: 10

Logging:
        Level: info
        Truncate: true

Mysql:
        Host: mysql.serlo.local:30000
        User: root
        Password: admin
        DBName: serlo
Postgres:
        Host: postgres.serlo.local
        Port: 30002
        User: postgres
        Password: admin
        DBName: kpi
        SSLMode: disable