Logging:
        Level: info
        Truncate: true

Mysql:
        Url: MINIKUBE_IP:30020
        User: root
        Password: admin
        DBName: serlo
Postgres:
        Host: MINIKUBE_IP
        Port: 30021
        User: postgres
        Password: admin
        DBName: kpi
        SSLMode: disable